
# итак настроим каждый сервис по отделности 
# каждый сервис переопределяет команду запуска

# задаем общюю сеть 
networks:
  api-network:
    driver: bridge

volumes:
  postgres_data:

services:
  # Готовые образы с DockerHub
  # API Gateway (Nginx)
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - auth-service
      - user-service
    networks:
      - api-network


  db:
    image: postgres:15-alpine
    container_name : db
    hostname: postgres
    restart: unless-stopped 
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: beregdonadb
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:                                
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d beregdonadb"]
      interval: 10s
      timeout: 5s
      retries: 5 
      start_period: 20s
    networks:
      - api-network 

  auth-service:
    build: .
    container_name: auth-service
    working_dir: /app/auth
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./services/auth:/app/auth
      - ./shared:/app/shared
      - ./.env:/app/.env
    command: 
      sh -c
      "
      uvicorn main:app --host 0.0.0.0 --port 8001
      "
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - api-network

  # Сервис пользователей
  user-service:
    build: .
    container_name: user-service
    working_dir: /app/user
    ports:
      - "8002:8002"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./services/user:/app/user
      - ./shared:/app/shared
      - ./.env:/app/.env
    command: 
      sh -c
      "
      uvicorn main:app --host 0.0.0.0 --port 8002
      "
    restart: unless-stopped
    depends_on:
      - auth-service
    networks:
      - api-network

  
  