version: '3.8'
# итак настроим каждый сервис по отделности 
# каждый сервис переопределяет команду запуска

# задаем общюю сеть 
networks:
  api-network:
    driver: bridge

services:

  # API Gateway (Nginx)
  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - auth-service
      - user-service
    networks:
      - api-network

  # Сервис авторизации
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      - SERVICE_PORT=8001
      - SERVICE_NAME=auth
    volumes:
      - ./auth:/app/auth
      - ./shared:/app/shared
      - ./.env:/app/.env
    command: ["python", "-m", "auth.main"]
    restart: unless-stopped
    networks:
      - api-network

  # Сервис пользователей
  user-service:
    build: .
    container_name: user-service
    ports:
      - "8002:8002"
    environment:
      - SERVICE_PORT=8002
      - SERVICE_NAME=user
      - AUTH_SERVICE_URL=http://auth-service:8001
    volumes:
      - ./user:/app/user
      - ./shared:/app/shared
      - ./.env:/app/.env
    command: ["python", "-m", "user.main"]
    restart: unless-stopped
    depends_on:
      - auth-service
    networks:
      - api-network

  
  